[project]
name = "gamestore"
version = "0.1.0"
dynamic = ["dependencies"]
readme = "README.md"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.scripts]
gamestore = "gamestore.__main__:main"
